INSERT INTO rk3.teachers VALUES('Sidorov Ivan Vasilyevich', 'IU-7', 6)
INSERT INTO rk3.teachers VALUES('Smirnov Nikolay Igorevich', 'IU-5', 3)
INSERT INTO rk3.teachers VALUES('Alexey Ivanovich Belousov', 'IU-7', 12)
INSERT INTO rk3.teachers VALUES('Georgiy Vladimirovich Karov', 'IU-8', 21)
INSERT INTO rk3.teachers VALUES('Natalia Gregorievna Ryazanova', 'RK-12', 14)

INSERT INTO rk3.students VALUES('Ivanov Ivan Ivanovich', '1990-09-25', 'IU-7', 'I dont know', 3)
INSERT INTO rk3.students VALUES('Petrov Petr Ivanovich', '1987-11-12', 'IU-8', 'Aliens', 4)
INSERT INTO rk3.students VALUES('Primak Viktor Viktorovich', '1993-08-05', 'RK-12', 'Cool hack system', 5)
INSERT INTO rk3.students VALUES('Sergeev Demian Demianov', '1996-12-28', 'IU-5', 'Meme analisis', NULL)