DROP PROC removeDubles

IF OBJECT_ID('LocalTable', 'U') IS NOT NULL
    DROP TABLE LocalTable
GO

CREATE TABLE LocalTable
(
    ID INT
)

INSERT INTO LocalTable VALUES(2)
INSERT INTO LocalTable VALUES(1)
INSERT INTO LocalTable VALUES(1)
INSERT INTO LocalTable VALUES(1)
INSERT INTO LocalTable VALUES(2)
INSERT INTO LocalTable VALUES(2)
INSERT INTO LocalTable VALUES(4)
INSERT INTO LocalTable VALUES(4)
INSERT INTO LocalTable VALUES(4)
INSERT INTO LocalTable VALUES(3)
INSERT INTO LocalTable VALUES(3)
INSERT INTO LocalTable VALUES(5)

SELECT * FROM LocalTable

EXEC removeDubles